- title: "{TVM}: An Automated {End-to-End} Optimizing Compiler for Deep Learning"
  venue: "osdi"
  venue_date: "2018.10"
  online_date: "2018.10"
  contacts: {}
  search_space:
  search_strategy:
  candidate_evaluation:
  discussed: true
  misc:
- title: "DANCE: Differentiable Accelerator/Network Co-Exploration"
  venue: "dac"
  venue_date: "2021.12"
  online_date: "2020.09"
  contacts: {"Kanghyun Choi": "kanghyun.choi@yonsei.ac.kr", "Jinho Lee": "leejinho@yonsei.ac.kr"}
  search_space:
  search_strategy: "differentiable"
  candidate_evaluation:
  discussed: true
  misc:
- title: "Hardware/Software Co-Exploration of Neural Architectures"
  venue: "IEEE_J_TCAD"
  venue_date: "2020.04"
  online_date: "2019.07"
  contacts: {"Weiwen Jiang": "wjiang2@nd.edu"}
  search_space:
  search_strategy:
  candidate_evaluation:
  discussed: true
  misc: